export const MockQuestions = [
    {
        id:1,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'4',
                id:4,
                data:{
                    title:'填空题',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'5',
                id:5,
                data:{
                    title:'多项填空题',
                    options:[
                        "填空项一",
                        "填空项二",
                        "填空项三"
                    ],
                    questions:[]
                }
            }
        ]
    },{
        id:2,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
        ]
    },{
        id:3,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
        ]
    },{
        id:4,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
        ]
    },{
        id:5,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
        ]
    },{
        id:6,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
        ]
    },{
        id:7,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
        ]
    },{
        id:8,
        title:{
            name:'示例问卷',
            describe:'欢迎使用问卷网！这是一份示例问卷'
        },
        questions:[
            {
                type:'1',
                id:1,
                data:{
                    title:'描述说明水电费',
                    options:[],
                    questions:[]
                }
            },
            {
                type:'2',
                id:2,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
            {
                type:'3',
                id:3,
                data:{
                    title:'默认文本',
                    options:[
                        "默认文本",
                        "默认文本",
                        "默认文本",
                        "默认文本"
                    ],
                    questions:[]
                }
            },
        ]
    }
];